package green.didikee.model;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "PERSON".
 */
@Entity
public class Person {

    @Id
    private Long id;

    @NotNull
    private String name;
    private Integer sex;
    private Integer age;
    private String nickName;
    private Long firstDate;
    private Long updateDate;
    private String phoneNumbers;
    private String emails;
    private Long noteCount;
    private Long likeCount;
    private Long badCount;
    private Long phoneCount;
    private Long smsCount;
    private Long sexCount;
    private Integer star;
    private String desc;
    private String subDesc;
    private Long birthday;
    private Integer constellation;
    private String tag;
    private String contactID;

    @Generated(hash = 1024547259)
    public Person() {
    }

    public Person(Long id) {
        this.id = id;
    }

    @Generated(hash = 1151030570)
    public Person(Long id, @NotNull String name, Integer sex, Integer age, String nickName, Long firstDate, Long updateDate, String phoneNumbers, String emails, Long noteCount, Long likeCount, Long badCount, Long phoneCount, Long smsCount, Long sexCount, Integer star, String desc, String subDesc, Long birthday, Integer constellation, String tag,
            String contactID) {
        this.id = id;
        this.name = name;
        this.sex = sex;
        this.age = age;
        this.nickName = nickName;
        this.firstDate = firstDate;
        this.updateDate = updateDate;
        this.phoneNumbers = phoneNumbers;
        this.emails = emails;
        this.noteCount = noteCount;
        this.likeCount = likeCount;
        this.badCount = badCount;
        this.phoneCount = phoneCount;
        this.smsCount = smsCount;
        this.sexCount = sexCount;
        this.star = star;
        this.desc = desc;
        this.subDesc = subDesc;
        this.birthday = birthday;
        this.constellation = constellation;
        this.tag = tag;
        this.contactID = contactID;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(@NotNull String name) {
        this.name = name;
    }

    public Integer getSex() {
        return sex;
    }

    public void setSex(Integer sex) {
        this.sex = sex;
    }

    public Integer getAge() {
        return age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    public String getNickName() {
        return nickName;
    }

    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    public Long getFirstDate() {
        return firstDate;
    }

    public void setFirstDate(Long firstDate) {
        this.firstDate = firstDate;
    }

    public Long getUpdateDate() {
        return updateDate;
    }

    public void setUpdateDate(Long updateDate) {
        this.updateDate = updateDate;
    }

    public String getPhoneNumbers() {
        return phoneNumbers;
    }

    public void setPhoneNumbers(String phoneNumbers) {
        this.phoneNumbers = phoneNumbers;
    }

    public String getEmails() {
        return emails;
    }

    public void setEmails(String emails) {
        this.emails = emails;
    }

    public Long getNoteCount() {
        return noteCount;
    }

    public void setNoteCount(Long noteCount) {
        this.noteCount = noteCount;
    }

    public Long getLikeCount() {
        return likeCount;
    }

    public void setLikeCount(Long likeCount) {
        this.likeCount = likeCount;
    }

    public Long getBadCount() {
        return badCount;
    }

    public void setBadCount(Long badCount) {
        this.badCount = badCount;
    }

    public Long getPhoneCount() {
        return phoneCount;
    }

    public void setPhoneCount(Long phoneCount) {
        this.phoneCount = phoneCount;
    }

    public Long getSmsCount() {
        return smsCount;
    }

    public void setSmsCount(Long smsCount) {
        this.smsCount = smsCount;
    }

    public Long getSexCount() {
        return sexCount;
    }

    public void setSexCount(Long sexCount) {
        this.sexCount = sexCount;
    }

    public Integer getStar() {
        return star;
    }

    public void setStar(Integer star) {
        this.star = star;
    }

    public String getDesc() {
        return desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }

    public String getSubDesc() {
        return subDesc;
    }

    public void setSubDesc(String subDesc) {
        this.subDesc = subDesc;
    }

    public Long getBirthday() {
        return birthday;
    }

    public void setBirthday(Long birthday) {
        this.birthday = birthday;
    }

    public Integer getConstellation() {
        return constellation;
    }

    public void setConstellation(Integer constellation) {
        this.constellation = constellation;
    }

    public String getTag() {
        return tag;
    }

    public void setTag(String tag) {
        this.tag = tag;
    }

    public String getContactID() {
        return contactID;
    }

    public void setContactID(String contactID) {
        this.contactID = contactID;
    }

}
